disbleJoinMessage: true
disableLeaveMessage: true
disablesendmessage: true
backmessage: "&eLoginUtils &f>> &cYou cannot say anything in Login Server."
HidePlayer: true
noDrop: true
noDropWorlds:
 - world
noHungry: true
noHungryWorlds:
 - world
noDamage: true
noDamageWorlds:
 - world
noWeather: true
noWeatherWorlds:
 - world
noBreak: true
noBreakWorlds:
 - world
noPlace: true
noPlaceWorlds:
 - world



